<?php 
namespace Zuz;

class Countries {

    private static $_LIST = [
        "AF" => ["name" => "Afghanistan", "continent" => "Asia"],
        "AX" => ["name" => "Åland Islands", "continent" => "Europe"],
        "AL" => ["name" => "Albania", "continent" => "Europe"],
        "DZ" => ["name" => "Algeria", "continent" => "Africa"],
        "AS" => ["name" => "American Samoa", "continent" => "Oceania"],
        "AD" => ["name" => "Andorra", "continent" => "Europe"],
        "AO" => ["name" => "Angola", "continent" => "Africa"],
        "AI" => ["name" => "Anguilla", "continent" => "North America"],
        "AQ" => ["name" => "Antarctica", "continent" => "Antarctica"],
        "AG" => ["name" => "Antigua and Barbuda", "continent" => "North America"],
        "AR" => ["name" => "Argentina", "continent" => "South America"],
        "AM" => ["name" => "Armenia", "continent" => "Asia"],
        "AW" => ["name" => "Aruba", "continent" => "North America"],
        "AU" => ["name" => "Australia", "continent" => "Oceania"],
        "AT" => ["name" => "Austria", "continent" => "Europe"],
        "AZ" => ["name" => "Azerbaijan", "continent" => "Asia"],
        "BS" => ["name" => "Bahamas", "continent" => "North America"],
        "BH" => ["name" => "Bahrain", "continent" => "Asia"],
        "BD" => ["name" => "Bangladesh", "continent" => "Asia"],
        "BB" => ["name" => "Barbados", "continent" => "North America"],
        "BY" => ["name" => "Belarus", "continent" => "Europe"],
        "BE" => ["name" => "Belgium", "continent" => "Europe"],
        "BZ" => ["name" => "Belize", "continent" => "North America"],
        "BJ" => ["name" => "Benin", "continent" => "Africa"],
        "BM" => ["name" => "Bermuda", "continent" => "North America"],
        "BT" => ["name" => "Bhutan", "continent" => "Asia"],
        "BO" => ["name" => "Bolivia", "continent" => "South America"],
        "BA" => ["name" => "Bosnia and Herzegovina", "continent" => "Europe"],
        "BW" => ["name" => "Botswana", "continent" => "Africa"],
        "BV" => ["name" => "Bouvet Island", "continent" => "Antarctica"],
        "BR" => ["name" => "Brazil", "continent" => "South America"],
        "IO" => ["name" => "British Indian Ocean Territory", "continent" => "Asia"],
        "BN" => ["name" => "Brunei Darussalam", "continent" => "Asia"],
        "BG" => ["name" => "Bulgaria", "continent" => "Europe"],
        "BF" => ["name" => "Burkina Faso", "continent" => "Africa"],
        "BI" => ["name" => "Burundi", "continent" => "Africa"],
        "KH" => ["name" => "Cambodia", "continent" => "Asia"],
        "CM" => ["name" => "Cameroon", "continent" => "Africa"],
        "CA" => ["name" => "Canada", "continent" => "North America"],
        "CV" => ["name" => "Cape Verde", "continent" => "Africa"],
        "KY" => ["name" => "Cayman Islands", "continent" => "North America"],
        "CF" => ["name" => "Central African Republic", "continent" => "Africa"],
        "TD" => ["name" => "Chad", "continent" => "Africa"],
        "CL" => ["name" => "Chile", "continent" => "South America"],
        "CN" => ["name" => "China", "continent" => "Asia"],
        "CX" => ["name" => "Christmas Island", "continent" => "Asia"],
        "CC" => ["name" => "Cocos (Keeling] Islands", "continent" => "Asia"],
        "CO" => ["name" => "Colombia", "continent" => "South America"],
        "KM" => ["name" => "Comoros", "continent" => "Africa"],
        "CG" => ["name" => "Congo", "continent" => "Africa"],
        "CD" => ["name" => "The Democratic Republic of The Congo", "continent" => "Africa"],
        "CK" => ["name" => "Cook Islands", "continent" => "Oceania"],
        "CR" => ["name" => "Costa Rica", "continent" => "North America"],
        "CI" => ["name" => "Cote D'ivoire", "continent" => "Africa"],
        "HR" => ["name" => "Croatia", "continent" => "Europe"],
        "CU" => ["name" => "Cuba", "continent" => "North America"],
        "CY" => ["name" => "Cyprus", "continent" => "Asia"],
        "CZ" => ["name" => "Czech Republic", "continent" => "Europe"],
        "DK" => ["name" => "Denmark", "continent" => "Europe"],
        "DJ" => ["name" => "Djibouti", "continent" => "Africa"],
        "DM" => ["name" => "Dominica", "continent" => "North America"],
        "DO" => ["name" => "Dominican Republic", "continent" => "North America"],
        "EC" => ["name" => "Ecuador", "continent" => "South America"],
        "EG" => ["name" => "Egypt", "continent" => "Africa"],
        "SV" => ["name" => "El Salvador", "continent" => "North America"],
        "GQ" => ["name" => "Equatorial Guinea", "continent" => "Africa"],
        "ER" => ["name" => "Eritrea", "continent" => "Africa"],
        "EE" => ["name" => "Estonia", "continent" => "Europe"],
        "ET" => ["name" => "Ethiopia", "continent" => "Africa"],
        "FK" => ["name" => "Falkland Islands (Malvinas]", "continent" => "South America"],
        "FO" => ["name" => "Faroe Islands", "continent" => "Europe"],
        "FJ" => ["name" => "Fiji", "continent" => "Oceania"],
        "FI" => ["name" => "Finland", "continent" => "Europe"],
        "FR" => ["name" => "France", "continent" => "Europe"],
        "GF" => ["name" => "French Guiana", "continent" => "South America"],
        "PF" => ["name" => "French Polynesia", "continent" => "Oceania"],
        "TF" => ["name" => "French Southern Territories", "continent" => "Antarctica"],
        "GA" => ["name" => "Gabon", "continent" => "Africa"],
        "GM" => ["name" => "Gambia", "continent" => "Africa"],
        "GE" => ["name" => "Georgia", "continent" => "Asia"],
        "DE" => ["name" => "Germany", "continent" => "Europe"],
        "GH" => ["name" => "Ghana", "continent" => "Africa"],
        "GI" => ["name" => "Gibraltar", "continent" => "Europe"],
        "GR" => ["name" => "Greece", "continent" => "Europe"],
        "GL" => ["name" => "Greenland", "continent" => "North America"],
        "GD" => ["name" => "Grenada", "continent" => "North America"],
        "GP" => ["name" => "Guadeloupe", "continent" => "North America"],
        "GU" => ["name" => "Guam", "continent" => "Oceania"],
        "GT" => ["name" => "Guatemala", "continent" => "North America"],
        "GG" => ["name" => "Guernsey", "continent" => "Europe"],
        "GN" => ["name" => "Guinea", "continent" => "Africa"],
        "GW" => ["name" => "Guinea-bissau", "continent" => "Africa"],
        "GY" => ["name" => "Guyana", "continent" => "South America"],
        "HT" => ["name" => "Haiti", "continent" => "North America"],
        "HM" => ["name" => "Heard Island and Mcdonald Islands", "continent" => "Antarctica"],
        "VA" => ["name" => "Holy See (Vatican City State]", "continent" => "Europe"],
        "HN" => ["name" => "Honduras", "continent" => "North America"],
        "HK" => ["name" => "Hong Kong", "continent" => "Asia"],
        "HU" => ["name" => "Hungary", "continent" => "Europe"],
        "IS" => ["name" => "Iceland", "continent" => "Europe"],
        "IN" => ["name" => "India", "continent" => "Asia"],
        "ID" => ["name" => "Indonesia", "continent" => "Asia"],
        "IR" => ["name" => "Iran", "continent" => "Asia"],
        "IQ" => ["name" => "Iraq", "continent" => "Asia"],
        "IE" => ["name" => "Ireland", "continent" => "Europe"],
        "IM" => ["name" => "Isle of Man", "continent" => "Europe"],
        "IL" => ["name" => "Israel", "continent" => "Asia"],
        "IT" => ["name" => "Italy", "continent" => "Europe"],
        "JM" => ["name" => "Jamaica", "continent" => "North America"],
        "JP" => ["name" => "Japan", "continent" => "Asia"],
        "JE" => ["name" => "Jersey", "continent" => "Europe"],
        "JO" => ["name" => "Jordan", "continent" => "Asia"],
        "KZ" => ["name" => "Kazakhstan", "continent" => "Asia"],
        "KE" => ["name" => "Kenya", "continent" => "Africa"],
        "KI" => ["name" => "Kiribati", "continent" => "Oceania"],
        "KP" => ["name" => "Democratic People's Republic of Korea", "continent" => "Asia"],
        "KR" => ["name" => "Republic of Korea", "continent" => "Asia"],
        "KW" => ["name" => "Kuwait", "continent" => "Asia"],
        "KG" => ["name" => "Kyrgyzstan", "continent" => "Asia"],
        "LA" => ["name" => "Lao People's Democratic Republic", "continent" => "Asia"],
        "LV" => ["name" => "Latvia", "continent" => "Europe"],
        "LB" => ["name" => "Lebanon", "continent" => "Asia"],
        "LS" => ["name" => "Lesotho", "continent" => "Africa"],
        "LR" => ["name" => "Liberia", "continent" => "Africa"],
        "LY" => ["name" => "Libya", "continent" => "Africa"],
        "LI" => ["name" => "Liechtenstein", "continent" => "Europe"],
        "LT" => ["name" => "Lithuania", "continent" => "Europe"],
        "LU" => ["name" => "Luxembourg", "continent" => "Europe"],
        "MO" => ["name" => "Macao", "continent" => "Asia"],
        "MK" => ["name" => "Macedonia", "continent" => "Europe"],
        "MG" => ["name" => "Madagascar", "continent" => "Africa"],
        "MW" => ["name" => "Malawi", "continent" => "Africa"],
        "MY" => ["name" => "Malaysia", "continent" => "Asia"],
        "MV" => ["name" => "Maldives", "continent" => "Asia"],
        "ML" => ["name" => "Mali", "continent" => "Africa"],
        "MT" => ["name" => "Malta", "continent" => "Europe"],
        "MH" => ["name" => "Marshall Islands", "continent" => "Oceania"],
        "MQ" => ["name" => "Martinique", "continent" => "North America"],
        "MR" => ["name" => "Mauritania", "continent" => "Africa"],
        "MU" => ["name" => "Mauritius", "continent" => "Africa"],
        "YT" => ["name" => "Mayotte", "continent" => "Africa"],
        "MX" => ["name" => "Mexico", "continent" => "North America"],
        "FM" => ["name" => "Micronesia", "continent" => "Oceania"],
        "MD" => ["name" => "Moldova", "continent" => "Europe"],
        "MC" => ["name" => "Monaco", "continent" => "Europe"],
        "MN" => ["name" => "Mongolia", "continent" => "Asia"],
        "ME" => ["name" => "Montenegro", "continent" => "Europe"],
        "MS" => ["name" => "Montserrat", "continent" => "North America"],
        "MA" => ["name" => "Morocco", "continent" => "Africa"],
        "MZ" => ["name" => "Mozambique", "continent" => "Africa"],
        "MM" => ["name" => "Myanmar", "continent" => "Asia"],
        "NA" => ["name" => "Namibia", "continent" => "Africa"],
        "NR" => ["name" => "Nauru", "continent" => "Oceania"],
        "NP" => ["name" => "Nepal", "continent" => "Asia"],
        "NL" => ["name" => "Netherlands", "continent" => "Europe"],
        "AN" => ["name" => "Netherlands Antilles", "continent" => "North America"],
        "NC" => ["name" => "New Caledonia", "continent" => "Oceania"],
        "NZ" => ["name" => "New Zealand", "continent" => "Oceania"],
        "NI" => ["name" => "Nicaragua", "continent" => "North America"],
        "NE" => ["name" => "Niger", "continent" => "Africa"],
        "NG" => ["name" => "Nigeria", "continent" => "Africa"],
        "NU" => ["name" => "Niue", "continent" => "Oceania"],
        "NF" => ["name" => "Norfolk Island", "continent" => "Oceania"],
        "MP" => ["name" => "Northern Mariana Islands", "continent" => "Oceania"],
        "NO" => ["name" => "Norway", "continent" => "Europe"],
        "OM" => ["name" => "Oman", "continent" => "Asia"],
        "PK" => ["name" => "Pakistan", "continent" => "Asia"],
        "PW" => ["name" => "Palau", "continent" => "Oceania"],
        "PS" => ["name" => "Palestinia", "continent" => "Asia"],
        "PA" => ["name" => "Panama", "continent" => "North America"],
        "PG" => ["name" => "Papua New Guinea", "continent" => "Oceania"],
        "PY" => ["name" => "Paraguay", "continent" => "South America"],
        "PE" => ["name" => "Peru", "continent" => "South America"],
        "PH" => ["name" => "Philippines", "continent" => "Asia"],
        "PN" => ["name" => "Pitcairn", "continent" => "Oceania"],
        "PL" => ["name" => "Poland", "continent" => "Europe"],
        "PT" => ["name" => "Portugal", "continent" => "Europe"],
        "PR" => ["name" => "Puerto Rico", "continent" => "North America"],
        "QA" => ["name" => "Qatar", "continent" => "Asia"],
        "RE" => ["name" => "Reunion", "continent" => "Africa"],
        "RO" => ["name" => "Romania", "continent" => "Europe"],
        "RU" => ["name" => "Russian Federation", "continent" => "Europe"],
        "RW" => ["name" => "Rwanda", "continent" => "Africa"],
        "SH" => ["name" => "Saint Helena", "continent" => "Africa"],
        "KN" => ["name" => "Saint Kitts and Nevis", "continent" => "North America"],
        "LC" => ["name" => "Saint Lucia", "continent" => "North America"],
        "PM" => ["name" => "Saint Pierre and Miquelon", "continent" => "North America"],
        "VC" => ["name" => "Saint Vincent and The Grenadines", "continent" => "North America"],
        "WS" => ["name" => "Samoa", "continent" => "Oceania"],
        "SM" => ["name" => "San Marino", "continent" => "Europe"],
        "ST" => ["name" => "Sao Tome and Principe", "continent" => "Africa"],
        "SA" => ["name" => "Saudi Arabia", "continent" => "Asia"],
        "SN" => ["name" => "Senegal", "continent" => "Africa"],
        "RS" => ["name" => "Serbia", "continent" => "Europe"],
        "SC" => ["name" => "Seychelles", "continent" => "Africa"],
        "SL" => ["name" => "Sierra Leone", "continent" => "Africa"],
        "SG" => ["name" => "Singapore", "continent" => "Asia"],
        "SK" => ["name" => "Slovakia", "continent" => "Europe"],
        "SI" => ["name" => "Slovenia", "continent" => "Europe"],
        "SB" => ["name" => "Solomon Islands", "continent" => "Oceania"],
        "SO" => ["name" => "Somalia", "continent" => "Africa"],
        "ZA" => ["name" => "South Africa", "continent" => "Africa"],
        "GS" => ["name" => "South Georgia and The South Sandwich Islands", "continent" => "Antarctica"],
        "ES" => ["name" => "Spain", "continent" => "Europe"],
        "LK" => ["name" => "Sri Lanka", "continent" => "Asia"],
        "SD" => ["name" => "Sudan", "continent" => "Africa"],
        "SR" => ["name" => "Suriname", "continent" => "South America"],
        "SJ" => ["name" => "Svalbard and Jan Mayen", "continent" => "Europe"],
        "SZ" => ["name" => "Swaziland", "continent" => "Africa"],
        "SE" => ["name" => "Sweden", "continent" => "Europe"],
        "CH" => ["name" => "Switzerland", "continent" => "Europe"],
        "SY" => ["name" => "Syrian Arab Republic", "continent" => "Asia"],
        "TW" => ["name" => "Taiwan, Province of China", "continent" => "Asia"],
        "TJ" => ["name" => "Tajikistan", "continent" => "Asia"],
        "TZ" => ["name" => "Tanzania, United Republic of", "continent" => "Africa"],
        "TH" => ["name" => "Thailand", "continent" => "Asia"],
        "TL" => ["name" => "Timor-leste", "continent" => "Asia"],
        "TG" => ["name" => "Togo", "continent" => "Africa"],
        "TK" => ["name" => "Tokelau", "continent" => "Oceania"],
        "TO" => ["name" => "Tonga", "continent" => "Oceania"],
        "TT" => ["name" => "Trinidad and Tobago", "continent" => "North America"],
        "TN" => ["name" => "Tunisia", "continent" => "Africa"],
        "TR" => ["name" => "Turkey", "continent" => "Asia"],
        "TM" => ["name" => "Turkmenistan", "continent" => "Asia"],
        "TC" => ["name" => "Turks and Caicos Islands", "continent" => "North America"],
        "TV" => ["name" => "Tuvalu", "continent" => "Oceania"],
        "UG" => ["name" => "Uganda", "continent" => "Africa"],
        "UA" => ["name" => "Ukraine", "continent" => "Europe"],
        "AE" => ["name" => "United Arab Emirates", "continent" => "Asia"],
        "GB" => ["name" => "United Kingdom", "continent" => "Europe"],
        "US" => ["name" => "United States", "continent" => "North America"],
        "UM" => ["name" => "United States Minor Outlying Islands", "continent" => "Oceania"],
        "UY" => ["name" => "Uruguay", "continent" => "South America"],
        "UZ" => ["name" => "Uzbekistan", "continent" => "Asia"],
        "VU" => ["name" => "Vanuatu", "continent" => "Oceania"],
        "VE" => ["name" => "Venezuela", "continent" => "South America"],
        "VN" => ["name" => "Viet Nam", "continent" => "Asia"],
        "VG" => ["name" => "Virgin Islands, British", "continent" => "North America"],
        "VI" => ["name" => "Virgin Islands, U.S.", "continent" => "North America"],
        "WF" => ["name" => "Wallis and Futuna", "continent" => "Oceania"],
        "EH" => ["name" => "Western Sahara", "continent" => "Africa"],
        "YE" => ["name" => "Yemen", "continent" => "Asia"],
        "ZM" => ["name" => "Zambia", "continent" => "Africa"],
        "ZW" => ["name" => "Zimbabwe", "continent" => "Africa"]
    ];

    public static function byCode($iso){
        return isset(self::$_LIST[$iso]) ? self::$_LIST[$iso] : array('name' => 'unknown');
    }

    public static function byName($nm){
        return self::$_LIST[$iso];
    }

    public static function Get(){
        return self::$_LIST;
    }

}
?>